name: Release

on:
  workflow_dispatch:
    inputs:
      username:
        description: Github username of the person triggering the release
        default: "Krzysztof-Cieslak"
        required: true
      email:
        description: Email of the person triggering the release
        default: "krzysztof_cieslak@windowslive.com"
        required: true

jobs:
  release:
    strategy:
      matrix:
        dotnet: [6.0.101]

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore
      run: dotnet restore -c Release
    - name: Run Build
      run: dotnet build --no-restore -c Release
    - name: Pack
      run: dotnet pack --no-restore -c Release -o packages
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: packages
    - name: Push packages
      uses: EasyDesk/action-nuget-push@v1
      with:
          nuget-api-key: ${{ secrets.NUGET_KEY }}
          publish-dir: packages