name: Release

on:
  push:
    tags:
    - 'v*'

jobs:
  release:
    strategy:
      matrix:
        dotnet: [6.0.101]

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
    - name: Restore
      run: dotnet restore -c Release
    - name: Run Build
      run: dotnet build --no-restore -c Release
    - name: Pack
      run: dotnet pack --no-restore -c Release -o packages
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.3.1
      with:
        path: packages
    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: packages/*.nupkg
        token: ${{ secrets.GITHUB_TOKEN }}
        generateReleaseNotes: true
    - name: Push packages
      uses: EasyDesk/action-nuget-push@v1
      with:
          nuget-api-key: ${{ secrets.NUGET_KEY }}
          publish-dir: packages
